const LOAD_USERS = "LOAD_USERS",
  LOAD_MESSAGES = "LOAD_MESSAGES",
  LOGIN_USER = "LOGIN_USER",
  LOGOUT_USER = "LOGOUT_USER";

export default { LOAD_USERS, LOAD_MESSAGES, LOGIN_USER, LOGOUT_USER };
