const ADD_SOCKET = "ADD_SOCKET",
  LOAD_USERS = "LOAD_USERS",
  LOAD_MESSAGES = "LOAD_MESSAGES",
  ADD_MESSAGE = "ADD_MESSAGE",
  LOGIN_USER = "LOGIN_USER",
  LOGOUT_USER = "LOGOUT_USER";

export default {
  ADD_SOCKET,
  LOAD_USERS,
  LOAD_MESSAGES,
  ADD_MESSAGE,
  LOGIN_USER,
  LOGOUT_USER
};
